Dashboard: fix sidebar #94
JULIERAJ/KIDS-FIRST-v2 pull request #123
Opened 2024-06-22 05:05 UTC by nadezdatsygankova

Sidebar Adjustments: Modified the sidebar for better responsiveness and UI consistency.
HomeDashboard, WeeksOverview, and Calendar Adjustments: Improved the design and functionality.
Icon Rendering Fix: Addressed the issue where icon text appeared briefly on page load.

Sidebar Adjustments
Styling Updates: Adjusted the sidebar width, margin, and padding for improved layout and usability.
Positioning: Made the sidebar position fixed with appropriate margins (top, bottom, right, left).

HomeDashboard, WeeksOverview, and Calendar Adjustments: Improved width

Solution for the icon issue: 
Preload fonts to ensure icons render consistently without fallback to text.
Implemented CSS to hide icons until fonts are fully loaded to maintain visual consistency.

2024-06-22 22:32 UTC, AnnaSolovykh requested changes
Wow, great job! 1/3 of the ticket is resolved, the hardest part is over! [Ticket](https://github.com/users/JULIERAJ/projects/2/views/1?pane=issue&itemId=67389226) - two other things are left to accomplish, and that is it with the sidebar for now!

2024-06-23 19:06 UTC, nadezdatsygankova commented
> Wow, great job! 1/3 of the ticket is resolved, the hardest part is over! [Ticket](https://github.com/users/JULIERAJ/projects/2/views/1?pane=issue&itemId=67389226) - two other things are left to accomplish, and that is it with the sidebar for now!

Fixed -Ensure Full Button Clickability: Make sure that the entire sidebar button is clickable, not just the link inside it, to improve the user experience.

2024-06-23 21:49 UTC, S-chahine approved these changes

2024-06-23 22:28 UTC, ElenaCherpakova approved these changes
LGTM!

2024-06-24 12:50 UTC, AnnaSolovykh approved these changes

2024-06-24 12:50 UTC, merged