Refactor/calendar/utils css
JULIERAJ/KIDS-FIRST-v2 pull request #92
Opened 2024-06-13 18:13 UTC by S-chahine

Details:

- Moved inline css styles from DayEvent, MonthEvent, and WeekEvent files into seperate css files.
- Combined the css styles for both DayEvent and MonthEvent into DayMonthEventStyles.css
- Moved Weekevent styles into seperate WeekEventStyles.css
- Moved isMultiDay and formatEventTime functions into dataUtils.jsx

2024-06-14 00:56 UTC, ElenaCherpakova reviewed
Where do we use this component or is it just a helper function?

2024-06-14 01:40 UTC, ElenaCherpakova commented
There is some small remarks: 
We name our CSS files just .css, which can lead to class name conflicts. To prevent this, please name your CSS files with the .module.css extension  like so `DayMonthEventStyle.module.css ` .  This will enable CSS modules, generating unique class names and preventing class name collisions.

2024-06-14 01:46 UTC, ElenaCherpakova requested changes

2024-06-14 01:46 UTC, ElenaCherpakova commented on frontend/src/components/Calendar/DayMonthEventStyles.css
> +.titleStyle {
could you please add module.css  to style file like so DayMonthEventStyles.module.css?

2024-06-14 18:17 UTC, S-chahine commented on frontend/src/components/Calendar/DayMonthEventStyles.css
> +.titleStyle {
I initially thought we only needed to change the names of the CSS files. However, it turns out that we also need to update the className assignments in the code. Should I proceed with making these changes now?

2024-06-14 22:23 UTC, S-chahine commented
I found out that the DayViewHeader function was originally placed in the DayEvent component, even though it is only used in KFCalendar. To improve the organization and maintainability of our code, I have moved the DayViewHeader function from DayEvent to the dateUtils file and imported it into KFCalendar.

2024-06-17 15:01 UTC, ElenaCherpakova commented on frontend/src/components/Calendar/DayMonthEventStyles.css
> +.titleStyle {
It wont require too much changes you just need to add module it and export it like so: 
import styles from './Button.module.css'; 
and add that styles before style name 
[Adding a CSS Modules Stylesheet](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)

2024-06-18 04:16 UTC, S-chahine commented on frontend/src/components/Calendar/DayMonthEventStyles.css
> +.titleStyle {
I've been working on modifying the CSS file names and updating the class names in the code. Unfortunately, the styles aren't coming through as intended.
I think the problem is that we're using React Big Calendar, and we're trying to override its default styles to match our Figma design. This seems to be causing some issues.
Do you have any ideas on how we can fix this while keeping our design consistent?

2024-06-19 14:09 UTC, ElenaCherpakova approved these changes

2024-06-19 17:55 UTC, merged